### ISSUE TITLE
ng build failed

### ISSUE THREAD

**Issue by datasmithtech** [angular-in-action/stocks#1]
Use of const in strict mode
....

at startup (node.js : 129:16)

i just did a git clone from your git repository
running on Windows 10
npm v 3.9.0
![ngbuilderror](https://cloud.githubusercontent.com/assets/2103016/22912178/adc466fc-f231-11e6-8430-8121616d9b4c.jpg)

**Comment by gnomeontherun** [comment]
What version of Node are you running, Angular CLI requires at leave Node v4 or greater.

https://github.com/angular/angular-cli/issues/3971
