### ISSUE TITLE
ng serve failed

### ISSUE THREAD

**Issue by datasmithtech** [angular-in-action/stocks#2]
![stockswebpackerror](https://cloud.githubusercontent.com/assets/2103016/22927314/8b6ce76c-f27e-11e6-8929-ea1cc8432673.jpg)

**Comment by gnomeontherun** [comment]
Did you resolve the issue found in #1? 

Please do 

```
node -v
npm -v
ng version
```

**Comment by datasmithtech** [comment]
I updated & retried
node 6.9.5
npm 4.3.0
ng 1.0.0-beta.18
[1m[31mERROR in [default] C:\stocks\node_modules\@types\jasmine\index.d.ts:39:37 
A parameter initializer is only allowed in a function or constructor implementation.[39m[22m

ERROR in [default] C:\stocks\node_modules\@types\jasmine\index.d.ts:39:45 
Cannot find name 'keyof'.

ERROR in [default] C:\stocks\node_modules\@types\jasmine\index.d.ts:39:51 
'=' expected.
Child  html-webpack-plugin for "index.html":
Chunk Names
    index.html[39m[22m  3.04 kB       [1m0[39m[22m  [1m[32m[39m[22m     
webpack: Failed to compile.

**Comment by datasmithtech** [comment]
Sorry, in spite of these errors, the app was up & running

I guess those errors only affect if you try to test the code, since i think it was related to Jasmine?
