### ISSUE TITLE
https://angularinaction.com/ is down 

### ISSUE THREAD

**Issue by andyserrato** [angular-in-action/stocks#3]
nice book but the API is down such a shame and I bought the book for nothing it seems

**Comment by gnomeontherun** [comment]
Hello, can you please share specifically what you are having an issue with? The API is not http://angularinaction.com but https://angular2-in-action-api.herokuapp.com. The API is running, and I'm happy to help debug the API if you can share some details so I know what to look for.

**Comment by andyserrato** [comment]
Hi, this request returns an empty object https://angular2-in-action-api.herokuapp.com/stocks/snapshot?symbols=aapl,goog,fb and the response is a 401 Unathorized. I've done it through the app and postman and responses are the same

**Comment by gnomeontherun** [comment]
Thanks for the report, it is a known bug in a dependency on Yahoo Finance :(. It appears they changed their API and removed some pieces. I'll report back when I've gotten it figured out, hopefully today.

**Comment by gnomeontherun** [comment]
I've pushed a fix for the API and checked my chapter 2 example. Let me know if it works for you!

**Comment by robphoenix** [comment]
I've tried this with Postman today and it works fine, output below. I believe this issue can be closed.

```json
[
    {
        "symbol": "AAPL",
        "lastTradePriceOnly": 221.07,
        "change": -2.7799988,
        "changeInPercent": -0.0124190245
    },
    {
        "symbol": "GOOG",
        "lastTradePriceOnly": 1162.82,
        "change": -14.540039,
        "changeInPercent": -0.012349698
    },
    {
        "symbol": "FB",
        "lastTradePriceOnly": 162,
        "change": -3.9400024,
        "changeInPercent": -0.023743536
    }
]
```
