### ISSUE TITLE
Section mdl-layout--large-screen-only empty page

### ISSUE THREAD

**Issue by kirillschwez** [angular-in-action/stocks#4]
Hello, just started reading a book "Angular in Action" and try to run first example
 
After adding line a have only blank page in browser.

```
 <div class="mdl-layout-spacer"></div>
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        <a class="mdl-navigation__link" [routerLink]="['/']">Dashboard</a>
        <a class="mdl-navigation__link" [routerLink]="['/manage']">Manage</a>        
      </nav>
    </div>
```
I figured out that empty page appears after adding links

```
<a class="mdl-navigation__link" [routerLink]="['/']">Dashboard</a>
<a class="mdl-navigation__link" [routerLink]="['/manage']">Manage</a>
```

without this snippet everything works, what can be a problem?
Many thanks!

**Comment by gnomeontherun** [comment]
Sorry I missed this, I would need more information about this to debug and probably there was some kind of error in the browser console that would have helped. If anyone finds this to be an issue let me know.
