### ISSUE TITLE
Page not showing up as it should.

### ISSUE THREAD

**Issue by BaseKernel** [angular-in-action/stocks#6]
Dear Jeremy,

I was following along in your book 'Angular in Action' and I did not get the expected output for 'Listning 2.4'. It does not error, but gives a very basic page: 

Stock Tracker
DashboardManage

I am working on a windows machine with the following settings, 'ng version':

Angular CLI: 13.3.4
Node: 16.15.0
Package Manager: npm 8.8.0
OS: win32 x64

Angular: 13.3.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                                        Version
---------------------------------------------------------
@angular-devkit/architect            0.1303.4
@angular-devkit/build-angular   13.3.4
@angular-devkit/core                  13.3.4
@angular-devkit/schematics       13.3.4
@angular/cli                                13.3.4
@schematics/angular                  13.3.4
rxjs                                                7.5.5
typescript                                     4.6.4

What versions do I need to have to follow along with the book? Thank you in advance!

**Comment by gnomeontherun** [comment]
Hello @BaseKernel the easiest way to proceed is to run this project directly. If you use the latest version of Angular, it won't always run code because TypeScript has evolved to have more strict rules. It also might be necessary to downgrade to Node v8 or v10. 

```
git clone https://github.com/angular-in-action/stocks.git
cd stocks
nom install
ng serve
```

The ecosystem evolves and the issues are not the code so much as the build tooling requirements.

**Comment by BaseKernel** [comment]
Thanks for your prompt reply. I believe you also need to downgrade Node. 

My objective was to get up to speed with angular and typescript and I have no experience in these areas. For this reason I decided to look for a more recent resource. No offense to you, the first 40 pages where very well written. I just think the gap between Angular 5 (my copy of ancular-in-action) and Angular 13 (current) is to great for me to cross right now.

Thanks for your help!

**Comment by gnomeontherun** [comment]
I've updated this example to Angular 15 if you are interested in trying it out, with the minor changes required for tooling.
